### ISSUE TITLE
(SMD V3) Left side gets chopped off when printing

### ISSUE THREAD

**Issue by cellularmitosis** [AchimPieters/SMD-Reference-Sheets#1]
Thank you so much for making these reference charts!

When I printed out the SMD reference V3 at 100% scale, I noticed that a small amount of the left hand side was chopped off (the first letter of every word is partially missing).

It looks like the size of the PDF is 11.7 x 8.27 inches, whereas letter-sized paper is 11 x 8.5 inches (and most printers cannot print all the way to the edge).

It looks like if you tightened up the horizontal layout by just a bit, it would print out onto standard letter-sized paper.

Thanks!

**Comment by AchimPieters** [comment]
@cellularmitosis thank you for your reply!

The PDF is made to be printed on A4 paper A4 | 210 × 297 | 8.3 × 11.7.
for more information see: https://www.swiftpublisher.com/useful-articles/paper-sizes-and-formats-explained
